### ISSUE TITLE
About `PURCHASE` Command

### ISSUE THREAD

**Issue by SENPAY98K** [chr233/ASFEnhance#80]
**Describe the bug / Bug 描述**
Hi, 
I don't know if it's a bug or not, but when i add for example 5 games to cart and buy for 100 bots, it only buy on about 15 accounts and nothing happens after that, and i think it's related to rate limits since we sending too much request.

```txt
ASFenhance 遇到错误, 日志如下
==========================================
 - 原始消息: TEST
 - Access: Owner
 - ASF 版本: 5.4.1.11
 - 插件版本: 1.7.9.0
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": false
}
==========================================
```

**Comment by chr233** [comment]
Please check this FAQ page of ArchiSteamFarm: https://github.com/JustArchiNET/ArchiSteamFarm/wiki/FAQ#did-somebody-get-banned-for-it

`
Please, use some common sense and don't assume that you can do such crazy things only because ASF allows you to do that. Doing loot ASF on over 1k of bots can be easily considered a [DDoS](https://en.wikipedia.org/wiki/DDoS) attack, and personally I'm not shocked that somebody got banned for such a thing. Keep in mind some bare common sense and minimum of fair use in regards to Steam service, and most likely you'll be fine.
`

Both ArchiSteamFarm and ASFEnhance are not designed to do like this, and your operation maybe cause temporary banned by ISP.

**Comment by SENPAY98K** [comment]
> Please check this FAQ page of ArchiSteamFarm: https://github.com/JustArchiNET/ArchiSteamFarm/wiki/FAQ#did-somebody-get-banned-for-it
> 
> `Please, use some common sense and don't assume that you can do such crazy things only because ASF allows you to do that. Doing loot ASF on over 1k of bots can be easily considered a [DDoS](https://en.wikipedia.org/wiki/DDoS) attack, and personally I'm not shocked that somebody got banned for such a thing. Keep in mind some bare common sense and minimum of fair use in regards to Steam service, and most likely you'll be fine.`
> 
> Both ArchiSteamFarm and ASFEnhance are not designed to do like this, and your operation maybe cause temporary banned by ISP.

Oh, i did not notice that. I was trying to lower the hassle of going through each account.
Well, it's fair enough. Thank you.
